### ISSUE TITLE
ERROR on creation of portalapi_publb_1 container

### ISSUE THREAD

**Issue by TESAARON** [Haufe-Lexware/wicked.haufe.io#11]
Hello,

I am encountering the following error when I run a 'docker-compose up' on my local instance. Any ideas what could be causing this?

$ docker-compose up -d --remove-orphans --force-recreate
Recreating portalapi_portal-api-data-static_1
Creating portalapi_portal-api-data-dynamic_1
Creating portalapi_kongdb-data_1
Creating portalapi_portal-api_1
Creating portalapi_kong-database_1
Creating portalapi_portal-mailer_1
Creating portalapi_kong_1
Creating portalapi_portal_1
Creating portalapi_portal-chatbot_1
Creating portalapi_portal-kong-adapter_1
Creating portalapi_publb_1

ERROR: for publb  Cannot start service publb: driver failed programming external connectivity on endpoint portalapi_publb_1 (578a9deb553e684847f11591a5a4f0a7602c356a5f7b6ad587cb40e24a6d96f4): Error starting userland proxy: mkdir /port/tcp:0.0.0.0:1936:tcp:172.19.0.9:1936: file exists
Encountered errors while bringing up the project.

Regards,
Aaron

**Comment by DonMartin76** [comment]
This is most probably caused by dangling network settings in docker. I have never seen it before though, and it has not been reported for Windows (yet) from the docker community. I just found this:

https://github.com/docker/compose/issues/3277

Try to remove all containers (except the dynamic data one, if that contains any data you want to keep), then try to remove all networks:

```
$ docker rm $(docker ps -aq) # this removes all containers
$ docker network rm $(docker network ls -q) # remove all networks
```

It can't hurt to restart Docker either. You're using Windows 10, and Docker 1.12.1?

**Comment by TESAARON** [comment]
Hi Martin,

Thanks for the response. Restart worked fine!

Regards,
Aaron
