### ISSUE TITLE
CORS issue when loading Swagger definition using TryIt if the Upstream API has Basic Auth

### ISSUE THREAD

**Issue by kbhuvanamohan** [Haufe-Lexware/wicked.haufe.io#134]
We are using wicked 0.12.5 and one of our upstream API has Basic Authentication enabled

- We can successfully load the swagger definition using the URL format: https://api.company.com/swagger-ui?https://developer.company.com/apis/api/swagger
- However, when trying to authorize the API by providing the username/credentials and clicking the "Authorize" button we are getting the CORS issue and the Swagger reload fails
- The above call is initiating a Pre-Flight OPTION call since it has an "authorize" header
- When further debugging the **/apis** route in the **wicked.portal**, CORS is enabled only for HTTP-GET and not for HTTP-OPTION for this route (Line# 315): https://github.com/apim-haufe-io/wicked.portal/blob/next/routes/apis.js
  
Please provide your guidance and opinion as to how to test via swagger for such authenticated upstream APIs

Thanks in advance for taking your time to look at this comment!

**Comment by DonMartin76** [comment]
Wicked does not support authenticating via Basic Auth (for the APIs), but I don't think that is the issue here. What it does support is adding a generic username/password as Basic Auth in the API configuration, so that your (dynamically allocated) clients can use API Keys or OAuth2 to get access to the API.

You can do that in the Kickstarter, in the "Custom Plugin" section; there is a "Add Authentication Header" functionality inside the "Toolbox":

<img width="1145" alt="image" src="https://user-images.githubusercontent.com/7326883/48206671-38494100-e36f-11e8-983c-3cc3b3dfc062.png">

You then would not use Basic Auth for your API, but rather API Keys or OAuth2 (Client Credentials).

Does this answer your question?

**Comment by kbhuvanamohan** [comment]
Thank you very much for your comments. It makes sense.
We will try this option and revert if we have any further queries.
Thanks again!

**Comment by kbhuvanamohan** [comment]
We manually place swagger definition within the static config so we don't need to retrieve it using the basic auth.

The solution you proposed is working fine and we can see the request-header plugin is added to the http://kong:8001/apis/[api-uuid]/plugin and the header is forwarded to the upstream.

You can close this issue.

Thanks!

**Comment by DonMartin76** [comment]
OK. If you feel you need the feature, feel free to open a new issue.

**Comment by kbhuvanamohan** [comment]
@miguelpoyatosmora
@karthiknaga87
Please help to provide additional information if needed and for your reference.
