### ISSUE TITLE
PORTAL IS RUNNING IN DEVELOPMENT MODE

### ISSUE THREAD

**Issue by Krieke** [Haufe-Lexware/wicked.haufe.io#43]
Which is the indicator for the wicked portal to indicate that the portal is running in development mode? We have created our own environment, but each time when we launch it, the portal display the (see title message) on every page bottom.

**Comment by DonMartin76** [comment]
The indicator is whether `globals.json:network.schema` is `http` or `https`. If this is `http` (which is not a good idea for anything facing the internet or even a potentially rogue environment), the portal assumes it's in development mode.

You will need to SSL terminate your port running the portal with some kind of either proxy or load balancer. In the default setup, this is HAproxy, with Kubernetes it might be an external load balancer or an ingress service, or even a cloud load balancer such as ELB or Azure LB.

The host names for `PORTAL_NETWORK_APIHOST` and `PORTAL_NETWORK_PORTALHOST` need to point to this TLS terminating component and these VHOSTs need to be registered with it to make the entire thing work securely and as intended. For testing purposes it's fine not to SSL terminate, but for a real deployment this is a MUST, and that's why the portal displays this quite obvious warning message.

Does this answer your question?

**Comment by Krieke** [comment]
Yep... this issue can be closed
