### ISSUE TITLE
WARNING: Environment variable PORTAL_MAILER_SMTP_HOST is defined but never used.

### ISSUE THREAD

**Issue by Krieke** [Haufe-Lexware/wicked.haufe.io#44]
The env checkbox for the env list in the title was enabled via "kickstarter" but when launching the wicked portal api we always notice : WARNING: Environment variable PORTAL_MAILER_SMTP_HOST is defined but never used..... this parameter was also configured in the end via the "kickstarter" tool but no mails are ever send out. We also notice the below error message although that the port is configured for smtps (which can only be configured via kickstarter and not via an environment variable).

{ Error: Greeting never received
    at SMTPConnection._formatError (/usr/src/app/node_modules/smtp-connection/lib/smtp-connection.js:493:15)
    at SMTPConnection._onError (/usr/src/app/node_modules/smtp-connection/lib/smtp-connection.js:479:16)
    at SMTPConnection.<anonymous> (/usr/src/app/node_modules/smtp-connection/lib/smtp-connection.js:420:18)
    at ontimeout (timers.js:365:14)
    at tryOnTimeout (timers.js:237:5)
    at Timer.listOnTimeout (timers.js:207:5) code: 'ETIMEDOUT', command: 'CONN' }

**Comment by DonMartin76** [comment]
OK, it seems as if your email configuration is off. This is always a little tricky as all email providers behave differently, but this looks as if the SMTP server is not responding at the address which is provided in the `globals.json` configuration.

The warning that `PORTAL_MAILER_SMTP_HOST` is not used means just that: There is an environment variable defined in either `default.json` or your `prod.json` (or whatever you called it) but it isn't used in any of the configuration JSON files. Check the `mailer` section of `globals.json` directly to try to track down what the issue is.

This is an example how it's configured for wicked-demo:

```json
  "mailer": {
    "useMailer": true,
    "senderEmail": "wicked-demo@haufe.io",
    "senderName": "wicked Demo API Portal",
    "smtpHost": "smtp.mailgun.org",
    "forceSecure": true,
    "username": "$PORTAL_MAILER_USERNAME",
    "password": "$PORTAL_MAILER_PASSWORD",
    "adminEmail": "martin.danielsson@haufe-lexware.com",
    "adminName": "Martin Danielsson"
  },
```

**Comment by Krieke** [comment]
The environment variable was called $PORTAL_MAILER_SMTPHOST ISO $PORTAL_MAILER_SMTP_HOST... the issue can be closed.
