### ISSUE TITLE
Issue creating portal-api repository on Windows

### ISSUE THREAD

**Issue by TESAARON** [Haufe-Lexware/wicked.haufe.io#8]
Hello,

I have managed to deploy the API portal on a separate Linux VM but as yet cannot get it running on my local Windows laptop. Docker is installed and running but when I run the command:

docker run -it --rm -v C:\Users\pc\Documents\api_portal:/var/portal-api -p 3333:3333 haufelexware/wicked.portal-kickstarter --new

I don't get any created files in the repo I created: C:\Users\pc\Documents\api_portal. I can view the kickstarter GUI at http://localhost:3333/ but no local files have been created. Any ideas why this command doesn't work for us on Windows but does on Linux?

**Comment by TESAARON** [comment]
Solution Found:

Go to Docker settings and shared drives. Enable the C: drive.

**Comment by DonMartin76** [comment]
Hi,

This is most probably due to the changed "Shared Folders" feature on Windows. On docker 1.11 and previous, mounting C:\Users and subfolders worked out of the box. With docker 1.12 (and above), you will first have to grant those rights to the Docker application, via

* Task Bar notification icon "docker" -> right click -> "Settings..."
* "Shared Drives"
* Tick the drive you need to share with docker

After that, it should work alright.

Please give a short note whether this works for you.

**Comment by TESAARON** [comment]
Hi Martin,

Yes this solution works perfectly.

Many thanks.
