### ISSUE TITLE
Missing support of Open Api/Swagger in YAML format

### ISSUE THREAD

**Issue by Kodrafo** [Haufe-Lexware/wicked.haufe.io#81]
I prefer the yaml format of a swagger file over the json format.
One reason is that more tools do support and prefer that format (Swagger Hub, Swagger Editor)
and from my point of view it is easier to read for humans.
I don't want to update/import the swagger file via Kickstarter. I want to replace it directly in the static folder of my API.

**Comment by DonMartin76** [comment]
Sounds like a good idea to support that. Shouldn't be too difficult.

**Comment by DonMartin76** [comment]
Currently this feature is not on the roadmap, and probably won't be either. The recommended way is to use the Swagger Lookup from the backend service, by adding a `swagger.json` file like this instead:

```
{
  "href":"http://service.whatever.svc.cluster.local:3000/api-docs/swagger"
}
```

This could be a sample lookup inside Kubernetes for a service called `service` running in the namespace `whatever`. The `swagger.json` also supports environment variables, so that you can use the same env var as for the upstream URL for example.
