### ISSUE TITLE
Deployment from a private repo does not work

### ISSUE THREAD

**Issue by HolgerNeub** [Haufe-Lexware/wicked.haufe.io#87]
If a repo with the configuration is in a non-public accessible git repo (e.g. In an intranet) the deployment does not work on a public platform with no access to the intranet. So the placement of the repo in a public available place is mandatory for the use of wicked.io on a public cloud.

**Comment by DonMartin76** [comment]
You may be right on that, yes. It would currently only work with the docker compose method which builds the static config container, but not with the git approach. Unless you have a VPN route or similar to your repository. Ideas or suggestions?

**Comment by DonMartin76** [comment]
I guess you are using Kubernetes, and for that I only have the following current bad workaround:

* Derive a custom image from `wicked.portal-api` and embed your configuration into `/var/portal-api/static`
* At every configuration change, push that updated image to a local registry
* Redeploy wicked, using your custom `portal-api` image instead of the vanilla `haufelexware/wicked.portal-api` image.

That means that you also need to adapt your build mechanism (update your `Dockerfile`) each time you want to update the wicked version.

Open to other suggestions how this might be solved in future versions of wicked.

It would be convenient to be able to use `ConfigMap`s, but those have a limit of 1 MB, which in most cases is not sufficient for an entire wicked configuration repo.

**Comment by DonMartin76** [comment]
Closing this for now. The official Kubernetes Chart will have support for this, using the `config.useCustomApiImage` and `config.customApiImage` properties in the `values.yaml`.
