### ISSUE TITLE
Allow no-key access/Public APIs/auth-type "none"

### ISSUE THREAD

**Issue by HolgerNeub** [Haufe-Lexware/wicked.haufe.io#96]
I would like to use wicked also for public apis with anonymous / no-key access. The reason for it is that I have 100% public apis (serving product packshots). 

For that API I want to have the portal to describe it and to have the raw data from the gateway for further statistics in another tool.

**Comment by nickruhl** [comment]
+1 to this enhancement. I was able to work around this by configuring kong directly. The "anonymous-user" does not show up in wicked but I was able to take an API that was set up via wicked and modify it to allow for anonymous access with these commands;

* Create new consumer, "anonymous-user"
** curl -i -X POST http://localhost:8001/consumers/ --data "username=anonymous_user"
* Enable Anonymous Access
**curl -i -X PATCH http://localhost:8001/plugins/{pluginID} --data "config.anonymous={anonymous_userID}"
* Add consumer ""anonymous_user" to ACL whitelist group.
** curl -i -X POST http://localhost:8001/consumers/{anonymous_userID}/acls --data "group={apigroup}"

It works and it does not appear that I have broken anything. @DonMartin76. Do you see any issues with manually modifying kong to allow anonymous access to an api?

**Comment by DonMartin76** [comment]
Yes, Kong Adapter might actually go and delete your "unknown consumer" when it's restarted... but let me check that. The Kong Adapter is a little touchy when it finds things it hasn't created.

**Comment by DonMartin76** [comment]
I checked the code, and the Kong Adapter will go through all consumers and delete anything it doesn't recognize. In addition, it will also throw out the "anonymous" field from the auth config the next time it tries to check the Kong configuration for that particular API.

This feature, how would you expect it to work?

I see two different possibilities:

* An API can be defined as purely "public"
* Or using Key-Auth or OAuth2 with an option "also enable anonymous access"

For the sake of simplicity, I think the first option is easier. Such APIs would necessarily be completely public (and thus not support `requiredGroup` either), and should possibly only support a few plugins. The rate limiting has to work slightly different, as it can't be "per credential", but rather "per IP" or similar.

Other things to consider?

**Comment by nickruhl** [comment]
So even creating the user through the portal and then enabling anonymous access for the API for the user created by the portal will not work because the anonymous field will be removed? Is there any way around this "for now" that you can think of? I am curious, why does the kong adapter remove the configs it did not make? Just curious and trying to learn more about this technology. :)

Thank you for looking into this. Solution #1 mostly works for my needs. Here is a little background of what I am trying to do. I have a client who wants to stand up a micro-gateway(mgw) within our environment. My first thought was to configure haproxy to route traffic directly to the mgw for only this api, bypassing kong but still using our domain. Then found the solution for anonymous-users within kong. I set up their mgw as an api within wicked and configured it to not authenticate which solved my issue, so solution #1 would work. Although, I would still need the requiredGroup functionality as I don't want to display this API to all users or publically. Oauth2 is handled by the clients mgw and upon authentication will pass the traffic to another api configured by wicked which will then pass the traffic to our backend mock service. I know its a little complicated. I would rather not have our clients mgw in the picture but I'm not sure if that is an option for us.

As for rate limiting, I am not too concerned about this right now, rate limiting all anonymous-users together is sufficient because we will not be having that much traffic going to this service. For the future, I could see by "IP" working well. I agree these "public" services should only support a few plugins.

I think for the future of wicked, having the ability to enable "multiple authentications" would come in handy to many users and I think enabling "anonymous-users" on a private service will be a use case many will want. Thank you again for what you have created. Please let me know what else I can elaborate on to help you understand my use case in any way.

**Comment by DonMartin76** [comment]
The reason the Kong Adapter behaves like this is fairly simple: It assumes to have complete control over Kong, with the exception of defined Kong plugins where you can add a list of plugins which the Kong Adapter will "leave alone". You can look at the Kong Adapter as a tool which looks at the state of the wicked API (registered clients and subscriptions) and then syncs all the settings it deems "correct" into Kong. If you have additional consumers, Kong Adapter will see that wicked does not want those and will subsequently delete them to make the states in wicked API and Kong API equal.

With other words, the Kong Adapter is a synchronization between wicked and Kong state, and if the states do not match (you have added fields or consumers for example), the Kong Adapter will change those the next time it looks at the corresponding entities.
---
As for the required group: It would possible to have the docs only visible for certain groups. It would not be possible to restrict the actual **access** to the API though - it's public. OK?

**Comment by nickruhl** [comment]
Thank you so much for explaining this to me. It all makes sense. As for the required groups. Solution #1 works for our needs as access is restricted by the mgw for this one use case. For others, it will be a nice feature to have a purely public api.

**Comment by DonMartin76** [comment]
Preliminary taking this into the scope of 1.0.0; there have been multiple requests for this.

**Comment by DonMartin76** [comment]
Fixed in 1.0.0-rc.4
